### ISSUE TITLE
Typo in RestService Instrument method.

### ISSUE THREAD

**Issue by ajoycekyrio** [pip-services3-dotnet/pip-services3-rpc-dotnet#3]
The Rest Service class in the file `RestService.cs` has a typo in the method `Instrument`

The counter line `_counters.IncrementOne(methodName + "exec_count");` is missing a period, it should read `_counters.IncrementOne(methodName + ".exec_count");`

This has the effect of creating a metric in prometheus with the following name `v1_references_get_referencesexec_count`, the correct metrics name would be `v1_references_get_references_exec_count`

**Comment by ajoycekyrio** [comment]
In the file `pip-services3-rpc-dotnet\src\Services\RestService.cs` on `line 183` the existing line `_counters.IncrementOne(methodName + "exec_count");` is missing a period.
Can you update the line to this `_counters.IncrementOne(methodName + ".exec_count");`

I am making updates to the prometheus library, that will require this fix to function correctly.

**Comment by Dvoikin** [comment]
@ajoycekyrio thanks for your comment. Updated the code and published a new version.

**Comment by Dvoikin** [comment]
@ajoycekyrio in 10 mins the new version should be available: 3.2.2.
