### ISSUE TITLE
CommandableHttpClient is missing the async await keywords

### ISSUE THREAD

**Issue by ajoycekyrio** [pip-services3-dotnet/pip-services3-rpc-dotnet#4]
**Error handling for a CommandableHttpClient is broken.**

The `CommandableHttpClient` is missing the `async await` keywords

This has the effect of calling the `finally` block after the `result = await _client.PostAsync(uri, content);` in the `ExecuteRequestAsync` method of the `RestClient` class.
This has the effect of skipping the `catch` block when an exception occurs.

The function where the issue occurs is below.
Adding `async` to the function and `await` to the `ExecuteAsync` call will fix the issue.

```
public Task<T> CallCommandAsync<T>(string route, string correlationId, object requestEntity)
            where T : class
{
	var timing = Instrument(correlationId, _baseRoute + "." + route);
	try
	{
		return ExecuteAsync<T>(correlationId, HttpMethod.Post, route, requestEntity);
	}
	catch (Exception ex)
	{
		InstrumentError(correlationId, _baseRoute + "." + route, ex);
		throw ex;
	}
	finally
	{
		timing.EndTiming();
	}
}
```

**Comment by Dvoikin** [comment]
@ajoycekyrio thank you! This update is included in the current version: 3.2.1.
