### ISSUE TITLE
Cannot serve https 

### ISSUE THREAD

**Issue by FaustZNOV** [pip-services3-dotnet/pip-services3-rpc-dotnet#5]
Creating an HttpEndpoint with the sss_key_file and ssl_crt_file credential fields specified in the documentation results in an "SSL password is not configured" error: 
![image](https://user-images.githubusercontent.com/77987927/129903624-975d728b-0f63-4196-b1a5-183ccaf63445.png)
![image](https://user-images.githubusercontent.com/77987927/129903681-877ccb08-6f65-4891-861a-2083fd897049.png)

Adding "ssl_password" results in a "SSL pfx file is not configured in credentials" error. After adding an "ssl_pfx_file", I see this error:
![image](https://user-images.githubusercontent.com/77987927/129904106-b59b6d06-9cbc-4f1f-a661-ae5ccb095fbd.png)

The last error may be from using the "ssl_pfx_file" as the file and password here? 
https://github.com/pip-services3-dotnet/pip-services3-rpc-dotnet/blob/ca30dc891c21970471bbfd0ace5021728872e134/src/Services/HttpEndpoint.cs#L219

**Comment by daniil-tr** [comment]
@FaustZNOV 
Thank you. I fixed this typo. 
Please continue using `ssl_pfx_file` and `ssl_password` parameters.
